### ISSUE TITLE
Issue on modal

### ISSUE THREAD

**Issue by averlius** [SharpMobileCode/ModalPickerViewController#10]
When i use this with any iphone or ipad works great, but when i open it from a modal view, it freezes the screen.

**Comment by SharpMobileCode** [comment]
That would make sense.  UIKit only allows you to show one modal view controller at a time.  ModalPickerViewController is shown modally with a custom transition delegate.  So if you try to show this from a view controller that's already shown modally, then it UIKit will have some issues.

**Comment by SharpMobileCode** [comment]
Or at least that's my assumption if I understand you correctly.  Could you provide a test project that re-creates the issue so that I can confirm this?

**Comment by averlius** [comment]
Oh yeah you are right about the two modals, it is not possible to show more than one, sorry for not being able to answer before, i came up with a different design for the app,  thanks for your time.
