### ISSUE TITLE
Classic API

### ISSUE THREAD

**Issue by Pirate911** [SharpMobileCode/ModalPickerViewController#12]
Hi , is there lib compilation for IOS classic API ?

**Comment by SharpMobileCode** [comment]
Hi there! Currently no, as Apple is no longer submitting apps that are built for 32-bit only (Classic API).  However, you can easily take the source and convert it back to Classic by changing nint back to int, etc.

--Ruben


-------- Original Message --------

**Comment by Pirate911** [comment]
I tried to change nint to int but I got errors about reference issue in UI...ModelView that needs UIKit namespace ...Is there anyway I get around it ?

**Comment by SharpMobileCode** [comment]
Well, yes you'll need to reference the old namespaces such as Monotouch.UIKit, instead of UIKit, and a few others.  Is there any reason you insist on using the classic API.  If you submit our app to the App Store, Apple is going to reject your app because it doesn't support 64-bit.

**Comment by Pirate911** [comment]
I didn't know that ..I will try to upgrade it to 64-bit and see how it goes ...thanks a lot man .

**Comment by SharpMobileCode** [comment]
No worries!  Here's a link to the Xamarin documentation that will help you convert.

https://developer.xamarin.com/guides/cross-platform/macios/unified/

**Comment by Pirate911** [comment]
You're the best !
