### ISSUE TITLE
Not working on iOS 9

### ISSUE THREAD

**Issue by cristianomad** [SharpMobileCode/ModalPickerViewController#13]
This component is not working properly with the final iOS9 SDK. It's not showing the option list.

**Comment by SharpMobileCode** [comment]
Just to confirm, you are compiling the project against the following components:

* iOS 9 SDK (not iOS 8.4)
* Xamarin Studio 5.9.7
* Xamarin.iOS 9.0.1.18

I'll take a look at it when I get home this evening.  Or if you have a pull request, I'll review that too.  Can you confirm you are using the versions stated above?

**Comment by cristianomad** [comment]
Yes. Exactly.

**Comment by SharpMobileCode** [comment]
Thanks! I'll take a look at it this evening after work.

**Comment by cristianomad** [comment]
Thanks. I'll try to fix too.

**Comment by SharpMobileCode** [comment]
Merge request accepted and appears to have fixed the issue when compiling against the iOS 9 SDK.  Thanks @cristianomad !!

**Comment by GregoryJames** [comment]
This fix works beautifully! Awesome work guys.

**Comment by mnandha** [comment]
We are using the same control on our Xamarin monotouch app as well and here is the code that's working in iOS 8.3 but not in 9. In 9, I don't see the calendar at all. Attached screenshots of 8.3 and 9. Any help is appreciated.

![sharpmobilecodedatepicker_83](https://cloud.githubusercontent.com/assets/7332944/10058331/824580aa-620a-11e5-898a-77278d9f87f9.PNG)
![sharpmobilecodedatepicker_90](https://cloud.githubusercontent.com/assets/7332944/10058330/824369be-620a-11e5-9396-c1e3edb4ca21.PNG)

**Comment by SharpMobileCode** [comment]
Pull down the latest source code as there is a fix.  If that still doesn't work, create a test project that re-creates the issue and post it on GitHub somewhere.

**Comment by mnandha** [comment]
Sorry my bad, made the change at the wrong place. :-)

It's working perfectly now, thanks a lot for the quick response.
